---
- hosts: 172.31.31.219
  become: yes
  tasks:
      - include_tasks: myfilehandle.yml

      - name: i want to create a file in ubuntu node
        apt:
            name: Apache2
            state: present