---
- hosts: all 
  become: yes
  tasks:
      - include_tasks: myfilehandle.yml

      - name: i want to create a file in ubuntu node
        apt:
            name: apache2
            state: present
        when: ansible_os_family == "Debian"

      - name: i want to create a file in redhat node
        yum:
            name: httpd
            state: present
        when: ansible_os_family == "RedHat"

      - name: i want replay apache2 template with my page
        template:
            src: mytemplate/mypage.j2
            dest: /var/www/html/index.html
        when: ansible_os_family == "Debian"