---
- hosts: 172.31.29.108
  become: yes
  tasks:
        - name: i want to install git
          apt:
              name: git
              state: present
          tags: mygit



        - name: i want to install tree
          apt:
              name: treeee
              state: present
          tags: mytree 
          ignore_errors: yes



        - name: i want to install wget
          apt:
              name: wget 
              state: present
          tags: mywget

        